spring.application.name=guide-svc

spring.datasource.url=jdbc:postgresql://localhost:5432/guide_svc
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.security.secret=f8bf1619-fc72-4de0-a970-da3bd8059268
jwt.security.trustedIssuers=auth-svc