spring.application.name=guide-svc

spring.datasource.url=jdbc:postgresql://localhost:5432/guide_svc
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect