spring.application.name=guide-svc

spring.datasource.url=jdbc:postgresql://localhost:5432/guide_svc
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.security.secret=35a196b6-0291-4911-8298-12fe38e7ac90
jwt.security.trustedIssuers=auth-svc
jwt.security.issuer=guide-svc